name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      env:
        DOCKER_PASSWORD: ${{ secrets.USER }}
        DOCKER_USERNAME: ${{ secrets.PASSWD }}
      run: |
        echo "$PASSWD" | docker login -u "$USER" --password-stdin

    - name: Build Docker image
      run: docker-compose build

    - name: Run tests
      run: docker-compose run test
      
    - name: Deploy
      run: docker-compose up -d
